[sources.sql_database.credentials]
host = "postgres_source"
port = "5432"
username = "user"
password = "password"
database = "mydatabase"
schema = "public"
drivername = "postgresql+psycopg2"

[destination.postgres.credentials]
host = "postgres_destination"
port = "5432"
username = "user"
password = "password"
database = "mydatabase"
schema = "public"
